# Generated by Django 3.2 on 2023-10-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('myfile', models.FileField(upload_to='media/%Y%m%d/')),
            ],
            options={
                'ordering': ('-update_time',),
            },
        ),
    ]
