# Generated by Django 3.2 on 2023-11-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='current_user',
        ),
    ]
