# Generated by Django 3.2 on 2023-10-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_auto_20231021_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('-update_time',)},
        ),
    ]
