# Generated by Django 3.2 on 2023-10-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_alter_folder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.folder', verbose_name='父文件夹'),
        ),
        migrations.AddField(
            model_name='folder',
            name='child_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folders', to='myfiles.folder', verbose_name='子文件夹'),
        ),
        migrations.AddField(
            model_name='folder',
            name='child_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='子父文件夹ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='myfiles.folder', verbose_name='父文件夹'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='父文件夹ID'),
        ),
    ]
