# Generated by Django 3.2 on 2023-10-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_auto_20231023_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='child_folder',
        ),
    ]
