# Generated by Django 3.2 on 2023-10-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_rename_folder_fileupload_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete time'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='%Y%m%d/'),
        ),
    ]
