# Generated by Django 3.2 on 2023-10-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_auto_20231027_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
