# Generated by Django 3.2 on 2023-10-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_recycled'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete time'),
        ),
    ]
