# Generated by Django 3.2 on 2023-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0011_folder_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='parent_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='父文件夹ID'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='父文件夹ID'),
        ),
    ]
