# Generated by Django 3.2 on 2023-10-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_auto_20231027_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='parent_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='父文件夹ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='父文件夹ID'),
        ),
    ]
