# Generated by Django 3.2 on 2023-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0013_auto_20231027_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='media/%Y%m%d/'),
        ),
    ]
